# November 9th - Pandas
# Создание столбцов на основе различных условий

In [1]:
from unittest.mock import inplace

import pandas as pd
import numpy as np

In [105]:
df = pd.read_csv('./Data/extraversion.csv')
df

,Unnamed: 0.1,Unnamed: 0,sex,volunteer,Q 1,Q 2,Q 3,Q 4,Q 5,Q 6,...,Q 48,Q 49,Q 50,Q 51,Q 52,Q 53,Q 54,Q 55,Q 56,Q 57
0,0,1,Женский,Нет,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Нет,Нет,Да
1,1,2,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет
2,2,3,Женский,Да,Да,Да,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Да,Нет,Нет,Да,Да,Нет
3,3,4,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Нет,Да,Да,Нет,Нет,Нет,Да,Нет,Нет
4,4,5,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Да,Да,Да,Да,Да,Нет
5,5,6,Женский,Нет,Да,Нет,Да,Да,Нет,Нет,...,Нет,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Нет
6,6,7,Женский,Нет,Да,Нет,Нет,Да,Да,Нет,...,Да,Да,Нет,Нет,Да,Да,Да,Да,Нет,Нет
7,7,8,Женский,Да,Да,Да,Да,Нет,Да,Да,...,Да,Да,Да,Нет,Да,Да,Да,Да,Да,Нет
8,8,9,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Да,Нет
9,9,10,Женский,Да,Да,Да,Нет,Нет,Да,Нет,...,Нет,Да,Нет,Нет,Нет,Да,Да,Да,Да,Нет
10,10,11,Мужской,Нет,Нет,Да,Нет,Нет,Да,Да,...,Да,Да,Нет,Да,Нет,Да,Да,Да,Да,Нет
11,11,12,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Да,Да,Да,Нет
12,12,13,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Да,Да
13,13,14,Женский,Нет,Да,Да,Нет,Да,Да,Нет,...,Да,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
14,14,15,Женский,Нет,Нет,Нет,Нет,Да,Да,Нет,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Нет,Нет
15,15,16,Женский,Нет,Да,Да,Да,Нет,Да,Нет,...,Да,Нет,Да,Нет,Да,Да,Да,Да,Да,Да
16,16,17,Женский,Нет,Да,Да,Нет,Нет,Нет,Да,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
17,17,18,Женский,Нет,Да,Нет,Да,Да,Нет,Нет,...,Да,Нет,Нет,Нет,Да,Нет,Нет,Да,Да,Нет
18,18,19,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет,Да
19,19,20,Женский,Нет,Нет,Нет,Да,Да,Да,Нет,...,Да,Нет,Да,Да,Да,Нет,Да,Нет,Да,Да
20,20,21,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
21,21,22,Женский,Да,Да,Да,Нет,Нет,Да,Нет,...,Нет,Нет,Нет,Нет,Да,Нет,Нет,Да,Нет,Нет
22,22,23,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Да,Нет,Да,Нет
23,23,24,Мужской,Да,Да,Да,Нет,Нет,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет
24,24,25,Мужской,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Нет,Да
25,25,26,Женский,Да,Нет,Да,Нет,Нет,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет,Нет
26,26,27,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Нет,Да,Да,Да,Да,Да,Нет,Да,Нет,Нет
27,27,28,Женский,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Да,Нет,Да,Нет,Да,Да,Да,Да,Нет
28,28,29,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Да,Да,Да,Нет,Нет,Да,Да,Да
29,29,30,Женский,Нет,Нет,Нет,Нет,Нет,Да,Да,...,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
30,30,31,Женский,Да,Да,Да,Нет,Да,Нет,Нет,...,Да,Нет,Да,Нет,Да,Нет,Нет,Нет,Да,Нет
31,31,32,Женский,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет
32,32,33,Женский,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Да,Нет,Нет
33,33,34,Мужской,Нет,Нет,Да,Нет,Да,Да,Нет,...,Да,Нет,Да,Нет,Да,Нет,Нет,Нет,Да,Нет
34,34,35,Женский,Нет,Да,Да,Да,Нет,Да,Да,...,Нет,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
35,35,36,Женский,Да,Да,Да,Нет,Да,Да,Нет,...,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет,Нет
36,36,37,Женский,Нет,Да,Да,Да,Нет,Да,Нет,...,Да,Да,Да,Нет,Да,Да,Да,Да,Да,Нет
37,37,38,Женский,Нет,Да,Нет,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
38,38,39,Женский,Нет,Да,Нет,Нет,Нет,Да,Нет,...,Да,Нет,Да,Нет,Нет,Нет,Нет,Да,Да,Да
39,39,40,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Да,Да
40,40,41,Женский,Нет,Да,Да,Нет,Нет,Да,Нет,...,Да,Да,Нет,Нет,Да,Да,Нет,Да,Нет,Да
41,41,42,Женский,Да,Да,Да,Нет,Нет,Да,Нет,...,Да,Нет,Нет,Нет,Да,Да,Да,Да,Да,Нет
42,42,43,Женский,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Нет,Да,Да,Да,Да,Нет,Да,Да,Нет
43,43,44,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет
44,44,45,Женский,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да
45,45,46,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Нет,Да,Нет,Да,Нет,Нет,Да,Да,Да
46,46,47,Женский,Да,Нет,Нет,Нет,Да,Да,Да,...,Да,Нет,Да,Нет,Да,Да,Нет,Да,Да,Нет
47,47,48,Женский,Нет,Нет,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Да,Нет,Нет,Нет
48,48,49,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Да,Да,Нет,Нет,Да,Да,Нет,Нет,Нет
49,49,50,Женский,Да,Нет,Нет,Нет,Нет,Да,Нет,...,Да,Нет,Да,Нет,Да,Нет,Да,Да,Да,Нет
50,50,51,Женский,Нет,Да,Да,Нет,Нет,Да,Нет,...,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Да,Да
51,51,52,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Да,Да,Да,Да,Да,Да,Нет,Нет

In [106]:
df.shape

(52, 61)

In [107]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [108]:
df

,Unnamed: 0.1,sex,volunteer,Q 1,Q 2,Q 3,Q 4,Q 5,Q 6,Q 7,...,Q 48,Q 49,Q 50,Q 51,Q 52,Q 53,Q 54,Q 55,Q 56,Q 57
0,0,Женский,Нет,Да,Нет,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Нет,Нет,Да
1,1,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет
2,2,Женский,Да,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Да,Нет,Нет,Да,Да,Нет
3,3,Женский,Нет,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Да,Да,Нет,Нет,Нет,Да,Нет,Нет
4,4,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Да,Да,Нет,Нет,Да,Да,Да,Да,Да,Нет
5,5,Женский,Нет,Да,Нет,Да,Да,Нет,Нет,Да,...,Нет,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Нет
6,6,Женский,Нет,Да,Нет,Нет,Да,Да,Нет,Да,...,Да,Да,Нет,Нет,Да,Да,Да,Да,Нет,Нет
7,7,Женский,Да,Да,Да,Да,Нет,Да,Да,Да,...,Да,Да,Да,Нет,Да,Да,Да,Да,Да,Нет
8,8,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Да,Нет
9,9,Женский,Да,Да,Да,Нет,Нет,Да,Нет,Да,...,Нет,Да,Нет,Нет,Нет,Да,Да,Да,Да,Нет
10,10,Мужской,Нет,Нет,Да,Нет,Нет,Да,Да,Нет,...,Да,Да,Нет,Да,Нет,Да,Да,Да,Да,Нет
11,11,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Да,Да,Да,Нет
12,12,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Да,Да
13,13,Женский,Нет,Да,Да,Нет,Да,Да,Нет,Да,...,Да,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
14,14,Женский,Нет,Нет,Нет,Нет,Да,Да,Нет,Да,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Нет,Нет
15,15,Женский,Нет,Да,Да,Да,Нет,Да,Нет,Да,...,Да,Нет,Да,Нет,Да,Да,Да,Да,Да,Да
16,16,Женский,Нет,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
17,17,Женский,Нет,Да,Нет,Да,Да,Нет,Нет,Да,...,Да,Нет,Нет,Нет,Да,Нет,Нет,Да,Да,Нет
18,18,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет,Да
19,19,Женский,Нет,Нет,Нет,Да,Да,Да,Нет,Да,...,Да,Нет,Да,Да,Да,Нет,Да,Нет,Да,Да
20,20,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
21,21,Женский,Да,Да,Да,Нет,Нет,Да,Нет,Да,...,Нет,Нет,Нет,Нет,Да,Нет,Нет,Да,Нет,Нет
22,22,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Да,Нет,Да,Нет
23,23,Мужской,Да,Да,Да,Нет,Нет,Да,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет
24,24,Мужской,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Нет,Да
25,25,Женский,Да,Нет,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет,Нет
26,26,Женский,Нет,Да,Да,Нет,Нет,Да,Да,Да,...,Нет,Да,Да,Да,Да,Да,Нет,Да,Нет,Нет
27,27,Женский,Да,Да,Нет,Нет,Нет,Да,Да,Нет,...,Да,Да,Нет,Да,Нет,Да,Да,Да,Да,Нет
28,28,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Да,Да,Да,Да,Нет,Нет,Да,Да,Да
29,29,Женский,Нет,Нет,Нет,Нет,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
30,30,Женский,Да,Да,Да,Нет,Да,Нет,Нет,Да,...,Да,Нет,Да,Нет,Да,Нет,Нет,Нет,Да,Нет
31,31,Женский,Да,Да,Нет,Нет,Нет,Да,Да,Нет,...,Да,Да,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет
32,32,Женский,Да,Да,Нет,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Да,Нет,Нет
33,33,Мужской,Нет,Нет,Да,Нет,Да,Да,Нет,Да,...,Да,Нет,Да,Нет,Да,Нет,Нет,Нет,Да,Нет
34,34,Женский,Нет,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
35,35,Женский,Да,Да,Да,Нет,Да,Да,Нет,Да,...,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет,Нет
36,36,Женский,Нет,Да,Да,Да,Нет,Да,Нет,Да,...,Да,Да,Да,Нет,Да,Да,Да,Да,Да,Нет
37,37,Женский,Нет,Да,Нет,Нет,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
38,38,Женский,Нет,Да,Нет,Нет,Нет,Да,Нет,Да,...,Да,Нет,Да,Нет,Нет,Нет,Нет,Да,Да,Да
39,39,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Да,Да
40,40,Женский,Нет,Да,Да,Нет,Нет,Да,Нет,Да,...,Да,Да,Нет,Нет,Да,Да,Нет,Да,Нет,Да
41,41,Женский,Да,Да,Да,Нет,Нет,Да,Нет,Да,...,Да,Нет,Нет,Нет,Да,Да,Да,Да,Да,Нет
42,42,Женский,Да,Да,Нет,Нет,Нет,Да,Да,Да,...,Да,Нет,Да,Да,Да,Да,Нет,Да,Да,Нет
43,43,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет
44,44,Женский,Да,Да,Нет,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да
45,45,Женский,Нет,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Да,Нет,Да,Нет,Нет,Да,Да,Да
46,46,Женский,Да,Нет,Нет,Нет,Да,Да,Да,Да,...,Да,Нет,Да,Нет,Да,Да,Нет,Да,Да,Нет
47,47,Женский,Нет,Нет,Нет,Нет,Да,Да,Да,Нет,...,Да,Нет,Нет,Да,Да,Нет,Да,Нет,Нет,Нет
48,48,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Да,Да,Нет,Нет,Да,Да,Нет,Нет,Нет
49,49,Женский,Да,Нет,Нет,Нет,Нет,Да,Нет,Да,...,Да,Нет,Да,Нет,Да,Нет,Да,Да,Да,Нет
50,50,Женский,Нет,Да,Да,Нет,Нет,Да,Нет,Да,...,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Да,Да
51,51,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Да,Да,Да,Да,Да,Да,Нет,Нет

In [109]:
df.groupby('sex')['volunteer'].count()

sex
Женский    48
Мужской     4
Name: volunteer, dtype: int64

In [110]:
df.groupby('volunteer')['sex'].count()

volunteer
Да     24
Нет    28
Name: sex, dtype: int64

In [111]:
df.describe

<bound method NDFrame.describe of     Unnamed: 0.1      sex volunteer  Q 1  Q 2  Q 3  Q 4  Q 5  Q 6  Q 7  ...  \
0              0  Женский       Нет   Да  Нет  Нет   Да   Да   Да   Да  ...
1              1  Женский        Да   Да   Да  Нет   Да   Да   Да   Да  ...
2              2  Женский        Да   Да   Да  Нет  Нет   Да   Да   Да  ...
3              3  Женский       Нет   Да   Да  Нет  Нет   Да   Да   Да  ...
4              4  Женский       Нет   Да   Да  Нет   Да   Да   Да   Да  ...
5              5  Женский       Нет   Да  Нет   Да   Да  Нет  Нет   Да  ...
6              6  Женский       Нет   Да  Нет  Нет   Да   Да  Нет   Да  ...
7              7  Женский        Да   Да   Да   Да  Нет   Да   Да   Да  ...
8              8  Женский       Нет   Да   Да  Нет   Да   Да   Да   Да  ...
9              9  Женский        Да   Да   Да  Нет  Нет   Да  Нет   Да  ...
10            10  Мужской       Нет  Нет   Да  Нет  Нет   Да   Да  Нет  ...
11            11  Женский        Да   Да   Да  Нет   Да   Да   Да   Да  ...
12            12  Женский        Да   Да   Да  Нет   Да   Да   Да   Да  ...
13            13  Женский       Нет   Да   Да  Нет   Да   Да  Нет   Да  ...
14            14  Женский       Нет  Нет  Нет  Нет   Да   Да  Нет   Да  ...
15            15  Женский       Нет   Да   Да   Да  Нет   Да  Нет   Да  ...
16            16  Женский       Нет   Да   Да  Нет  Нет  Нет   Да   Да  ...
17            17  Женский       Нет   Да  Нет   Да   Да  Нет  Нет   Да  ...
18            18  Женский       Нет   Да   Да  Нет   Да   Да   Да   Да  ...
19            19  Женский       Нет  Нет  Нет   Да   Да   Да  Нет   Да  ...
20            20  Женский       Нет   Да   Да  Нет   Да   Да   Да   Да  ...
21            21  Женский        Да   Да   Да  Нет  Нет   Да  Нет   Да  ...
22            22  Женский       Нет   Да   Да  Нет   Да   Да   Да   Да  ...
23            23  Мужской        Да   Да   Да  Нет  Нет   Да   Да   Да  ...
24            24  Мужской        Да   Да   Да  Нет   Да   Да   Да   Да  ...
25            25  Женский        Да  Нет   Да  Нет  Нет   Да   Да   Да  ...
26            26  Женский       Нет   Да   Да  Нет  Нет   Да   Да   Да  ...
27            27  Женский        Да   Да  Нет  Нет  Нет   Да   Да  Нет  ...
28            28  Женский        Да   Да   Да  Нет   Да   Да   Да   Да  ...
29            29  Женский       Нет  Нет  Нет  Нет  Нет   Да   Да   Да  ...
30            30  Женский        Да   Да   Да  Нет   Да  Нет  Нет   Да  ...
31            31  Женский        Да   Да  Нет  Нет  Нет   Да   Да  Нет  ...
32            32  Женский        Да   Да  Нет  Нет  Нет   Да   Да   Да  ...
33            33  Мужской       Нет  Нет   Да  Нет   Да   Да  Нет   Да  ...
34            34  Женский       Нет   Да   Да   Да  Нет   Да   Да   Да  ...
35            35  Женский        Да   Да   Да  Нет   Да   Да  Нет   Да  ...
36            36  Женский       Нет   Да   Да   Да  Нет   Да  Нет   Да  ...
37            37  Женский       Нет   Да  Нет  Нет  Нет   Да   Да   Да  ...
38            38  Женский       Нет   Да  Нет  Нет  Нет   Да  Нет   Да  ...
39            39  Женский        Да   Да   Да  Нет   Да   Да   Да   Да  ...
40            40  Женский       Нет   Да   Да  Нет  Нет   Да  Нет   Да  ...
41            41  Женский        Да   Да   Да  Нет  Нет   Да  Нет   Да  ...
42            42  Женский        Да   Да  Нет  Нет  Нет   Да   Да   Да  ...
43            43  Женский       Нет   Да   Да  Нет   Да   Да   Да   Да  ...
44            44  Женский        Да   Да  Нет  Нет   Да   Да   Да   Да  ...
45            45  Женский       Нет   Да   Да  Нет  Нет   Да   Да   Да  ...
46            46  Женский        Да  Нет  Нет  Нет   Да   Да   Да   Да  ...
47            47  Женский       Нет  Нет  Нет  Нет   Да   Да   Да  Нет  ...
48            48  Женский        Да   Да   Да  Нет   Да   Да   Да   Да  ...
49            49  Женский        Да  Нет  Нет  Нет  Нет   Да  Нет   Да  ...
50            50  Женский       Нет   Да   Да  Нет  Нет   Да  Нет   Да  ...
51            51  Женский        Да   Да   Да  Нет   Да   Да   Да   Да  ...

   Q 48 Q 49 Q 50 Q 51 Q 52 Q 53 Q 54 Q 55 Q 56 Q 57
0    Да  Нет  Нет   Да   Да  Нет  Нет  Нет  Нет   Да
1    Да   Да  Нет  Нет  Нет   Да  Нет   Да   Да  Нет
2    Да   Да  Нет  Нет   Да  Нет  Нет   Да   Да  Нет
3    Да  Нет   Да   Да  Нет  Нет  Нет   Да  Нет  Нет
4    Да   Да  Нет  Нет   Да   Да   Да   Да   Да  Нет
5   Нет   Да  Нет  Нет  Нет   Да   Да  Нет   Да  Нет
6    Да   Да  Нет  Нет   Да   Да   Да   Да  Нет  Нет
7    Да   Да   Да  Нет   Да   Да   Да   Да   Да  Нет
8    Да  Нет  Нет  Нет   Да   Да  Нет   Да   Да  Нет
9   Нет   Да  Нет  Нет  Нет   Да   Да   Да   Да  Нет
10   Да   Да  Нет   Да  Нет   Да   Да   Да   Да  Нет
11  Нет   Да  Нет  Нет   Да   Да   Да   Да   Да  Нет
12   Да  Нет  Нет  Нет   Да  Нет   Да   Да   Да   Да
13   Да   Да  Нет  Нет  Нет  Нет  Нет   Да  Нет  Нет
14   Да  Нет   Да   Да   Да  Нет   Да   Да  Нет  Нет
15   Да  Нет   Да  Нет   Да   Да   Да   Да   Да   Да
16   Да  Нет   Да   Да   Да  Нет   Да   Да   Да  Нет
17   Да  Нет  Нет  Нет   Да  Нет  Нет   Да   Да  Нет
18   Да  Нет  Нет  Нет   Да  Нет   Да   Да  Нет   Да
19   Да  Нет   Да   Да   Да  Нет   Да  Нет   Да   Да
20  Нет  Нет   Да   Да   Да  Нет   Да   Да   Да  Нет
21  Нет  Нет  Нет  Нет   Да  Нет  Нет   Да  Нет  Нет
22  Нет   Да  Нет  Нет   Да   Да   Да  Нет   Да  Нет
23  Нет   Да  Нет  Нет   Да   Да  Нет   Да   Да  Нет
24   Да  Нет   Да   Да   Да  Нет   Да   Да  Нет   Да
25   Да  Нет  Нет   Да   Да  Нет   Да   Да  Нет  Нет
26  Нет   Да   Да   Да   Да   Да  Нет   Да  Нет  Нет
27   Да   Да  Нет   Да  Нет   Да   Да   Да   Да  Нет
28  Нет   Да   Да   Да   Да  Нет  Нет   Да   Да   Да
29  Нет  Нет   Да   Да   Да  Нет   Да   Да   Да  Нет
30   Да  Нет   Да  Нет   Да  Нет  Нет  Нет   Да  Нет
31   Да   Да  Нет  Нет   Да  Нет  Нет  Нет   Да  Нет
32   Да  Нет  Нет   Да   Да  Нет  Нет   Да  Нет  Нет
33   Да  Нет   Да  Нет   Да  Нет  Нет  Нет   Да  Нет
34  Нет   Да  Нет  Нет  Нет  Нет  Нет   Да  Нет  Нет
35   Да  Нет  Нет   Да   Да  Нет   Да   Да  Нет  Нет
36   Да   Да   Да  Нет   Да   Да   Да   Да   Да  Нет
37   Да   Да  Нет  Нет  Нет  Нет  Нет   Да  Нет  Нет
38   Да  Нет   Да  Нет  Нет  Нет  Нет   Да   Да   Да
39   Да  Нет  Нет  Нет   Да  Нет   Да   Да   Да   Да
40   Да   Да  Нет  Нет   Да   Да  Нет   Да  Нет   Да
41   Да  Нет  Нет  Нет   Да   Да   Да   Да   Да  Нет
42   Да  Нет   Да   Да   Да   Да  Нет   Да   Да  Нет
43   Да  Нет  Нет  Нет   Да  Нет  Нет  Нет   Да  Нет
44   Да  Нет  Нет   Да   Да   Да  Нет   Да   Да   Да
45   Да  Нет   Да  Нет   Да  Нет  Нет   Да   Да   Да
46   Да  Нет   Да  Нет   Да   Да  Нет   Да   Да  Нет
47   Да  Нет  Нет   Да   Да  Нет   Да  Нет  Нет  Нет
48   Да   Да   Да  Нет  Нет   Да   Да  Нет  Нет  Нет
49   Да  Нет   Да  Нет   Да  Нет   Да   Да   Да  Нет
50   Да  Нет  Нет  Нет   Да   Да  Нет   Да   Да   Да
51   Да  Нет   Да   Да   Да   Да   Да   Да  Нет  Нет

[52 rows x 60 columns]>

In [112]:
df.columns

Index(['Unnamed: 0.1', 'sex', 'volunteer', 'Q 1', 'Q 2', 'Q 3', 'Q 4', 'Q 5',
       'Q 6', 'Q 7', 'Q 8', 'Q 9', 'Q 10', 'Q 11', 'Q 12', 'Q 13', 'Q 14',
       'Q 15', 'Q 16', 'Q 17', 'Q 18', 'Q 19', 'Q 20', 'Q 21', 'Q 22', 'Q 23',
       'Q 24', 'Q 25', 'Q 26', 'Q 27', 'Q 28', 'Q 29', 'Q 30', 'Q 31', 'Q 32',
       'Q 33', 'Q 34', 'Q 35', 'Q 36', 'Q 37', 'Q 38', 'Q 39', 'Q 40', 'Q 41',
       'Q 42', 'Q 43', 'Q 44', 'Q 45', 'Q 46', 'Q 47', 'Q 48', 'Q 49', 'Q 50',
       'Q 51', 'Q 52', 'Q 53', 'Q 54', 'Q 55', 'Q 56', 'Q 57'],
      dtype='object')

In [113]:
df.columns = df.columns.map(lambda x: x.replace(' ', ''))
df.head(2)

,Unnamed:0.1,sex,volunteer,Q1,Q2,Q3,Q4,Q5,Q6,Q7,...,Q48,Q49,Q50,Q51,Q52,Q53,Q54,Q55,Q56,Q57
0,0,Женский,Нет,Да,Нет,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Нет,Нет,Да
1,1,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет

In [114]:
print(list(df.columns)[3:])

['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21', 'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30', 'Q31', 'Q32', 'Q33', 'Q34', 'Q35', 'Q36', 'Q37', 'Q38', 'Q39', 'Q40', 'Q41', 'Q42', 'Q43', 'Q44', 'Q45', 'Q46', 'Q47', 'Q48', 'Q49', 'Q50', 'Q51', 'Q52', 'Q53', 'Q54', 'Q55', 'Q56', 'Q57']

In [115]:
extra_yes = df[['Q1', 'Q3', 'Q8', 'Q10', 'Q13', 'Q17', 'Q22', 'Q23', 'Q24', 'Q25', 'Q27', 'Q39', 'Q44', 'Q46', 'Q49', 'Q53', 'Q56']]

In [116]:
extra_no = df[['Q5', 'Q15', 'Q20', 'Q29', 'Q30', 'Q32', 'Q34', 'Q37', 'Q41', 'Q51']]

In [117]:
extra_yes.isin(['Да']).sum()

Q1     43
Q3      7
Q8     15
Q10    11
Q13    33
Q17    34
Q22    12
Q23    30
Q24     6
Q25    37
Q27    37
Q39    22
Q44    11
Q46    27
Q49    21
Q53    23
Q56    34
dtype: int64

In [118]:
extra_no.isin(['Нет']).sum()

Q5      4
Q15    38
Q20     6
Q29    26
Q30     8
Q32    26
Q34    23
Q37    27
Q41    43
Q51    33
dtype: int64

In [119]:
df['extra'] = extra_yes.isin(['Да']).sum(axis=1) + extra_no.isin(['Нет']).sum(axis=1)
df.head()

,Unnamed:0.1,sex,volunteer,Q1,Q2,Q3,Q4,Q5,Q6,Q7,...,Q49,Q50,Q51,Q52,Q53,Q54,Q55,Q56,Q57,extra
0,0,Женский,Нет,Да,Нет,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Да,Нет,Нет,Нет,Нет,Да,7
1,1,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет,16
2,2,Женский,Да,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Нет,Нет,Да,Да,Нет,13
3,3,Женский,Нет,Да,Да,Нет,Нет,Да,Да,Да,...,Нет,Да,Да,Нет,Нет,Нет,Да,Нет,Нет,5
4,4,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Да,Да,Да,Нет,14

In [120]:
df['volunteer_num'] = np.where(df['volunteer'] == 'Да', 1, 0) 
df.head(5)

,Unnamed:0.1,sex,volunteer,Q1,Q2,Q3,Q4,Q5,Q6,Q7,...,Q50,Q51,Q52,Q53,Q54,Q55,Q56,Q57,extra,volunteer_num
0,0,Женский,Нет,Да,Нет,Нет,Да,Да,Да,Да,...,Нет,Да,Да,Нет,Нет,Нет,Нет,Да,7,0
1,1,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Нет,Да,Нет,Да,Да,Нет,16,1
2,2,Женский,Да,Да,Да,Нет,Нет,Да,Да,Да,...,Нет,Нет,Да,Нет,Нет,Да,Да,Нет,13,1
3,3,Женский,Нет,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Нет,5,0
4,4,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Да,Да,Нет,14,0

In [121]:
pure = df[((df['volunteer'].isin(['Да'])) & (df['extra'] > 15)) | (df['volunteer'].isin(['Нет'])) & (df['extra'] < 15)]
pure

,Unnamed:0.1,sex,volunteer,Q1,Q2,Q3,Q4,Q5,Q6,Q7,...,Q50,Q51,Q52,Q53,Q54,Q55,Q56,Q57,extra,volunteer_num
0,0,Женский,Нет,Да,Нет,Нет,Да,Да,Да,Да,...,Нет,Да,Да,Нет,Нет,Нет,Нет,Да,7,0
1,1,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Нет,Да,Нет,Да,Да,Нет,16,1
3,3,Женский,Нет,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Нет,5,0
4,4,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Да,Да,Нет,14,0
7,7,Женский,Да,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Да,Да,Да,Да,Да,Нет,21,1
8,8,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Да,Нет,Да,Да,Нет,13,0
9,9,Женский,Да,Да,Да,Нет,Нет,Да,Нет,Да,...,Нет,Нет,Нет,Да,Да,Да,Да,Нет,20,1
10,10,Мужской,Нет,Нет,Да,Нет,Нет,Да,Да,Нет,...,Нет,Да,Нет,Да,Да,Да,Да,Нет,8,0
11,11,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Да,Да,Нет,17,1
14,14,Женский,Нет,Нет,Нет,Нет,Да,Да,Нет,Да,...,Да,Да,Да,Нет,Да,Да,Нет,Нет,7,0
16,16,Женский,Нет,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Да,Да,Нет,Да,Да,Да,Нет,14,0
18,18,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Нет,Да,Да,Нет,Да,12,0
19,19,Женский,Нет,Нет,Нет,Да,Да,Да,Нет,Да,...,Да,Да,Да,Нет,Да,Нет,Да,Да,10,0
20,20,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Да,Да,Да,Нет,Да,Да,Да,Нет,12,0
23,23,Мужской,Да,Да,Да,Нет,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Нет,Да,Да,Нет,18,1
26,26,Женский,Нет,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Да,Да,Да,Нет,Да,Нет,Нет,14,0
29,29,Женский,Нет,Нет,Нет,Нет,Нет,Да,Да,Да,...,Да,Да,Да,Нет,Да,Да,Да,Нет,3,0
33,33,Мужской,Нет,Нет,Да,Нет,Да,Да,Нет,Да,...,Да,Нет,Да,Нет,Нет,Нет,Да,Нет,9,0
34,34,Женский,Нет,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет,10,0
37,37,Женский,Нет,Да,Нет,Нет,Нет,Да,Да,Да,...,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет,9,0
38,38,Женский,Нет,Да,Нет,Нет,Нет,Да,Нет,Да,...,Да,Нет,Нет,Нет,Нет,Да,Да,Да,11,0
40,40,Женский,Нет,Да,Да,Нет,Нет,Да,Нет,Да,...,Нет,Нет,Да,Да,Нет,Да,Нет,Да,12,0
43,43,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет,11,0
47,47,Женский,Нет,Нет,Нет,Нет,Да,Да,Да,Нет,...,Нет,Да,Да,Нет,Да,Нет,Нет,Нет,3,0
48,48,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Нет,18,1
50,50,Женский,Нет,Да,Да,Нет,Нет,Да,Нет,Да,...,Нет,Нет,Да,Да,Нет,Да,Да,Да,13,0

In [122]:
pure['volunteer'].isin(['Да']).sum()

np.int64(6)

In [123]:
pure['volunteer'].isin(['Нет']).sum()

np.int64(20)

In [124]:
pure['extra'].min()

np.int64(3)

In [125]:
pure['extra'].apply([min, max, np.mean, np.median])

min        3.000000
max       21.000000
mean      11.807692
median    12.000000
Name: extra, dtype: float64

# Даже если мы хотим использовать метод apply с одной функцией, все равно необходимо брать все содержимое в квадратные скобки

In [126]:
pure['extra'].apply([min])

min    3
Name: extra, dtype: int64

# Игнорируем предупреждения

In [127]:
import warnings
warnings.filterwarnings('ignore')

In [128]:
pure['high'] = np.where (pure['extra'] > 11, 1, 0)
pure.head()

,Unnamed:0.1,sex,volunteer,Q1,Q2,Q3,Q4,Q5,Q6,Q7,...,Q51,Q52,Q53,Q54,Q55,Q56,Q57,extra,volunteer_num,high
0,0,Женский,Нет,Да,Нет,Нет,Да,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Нет,Да,7,0,0
1,1,Женский,Да,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Нет,Да,Нет,Да,Да,Нет,16,1,1
3,3,Женский,Нет,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Нет,5,0,0
4,4,Женский,Нет,Да,Да,Нет,Да,Да,Да,Да,...,Нет,Да,Да,Да,Да,Да,Нет,14,0,1
7,7,Женский,Да,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Да,Да,Да,Да,Нет,21,1,1

In [134]:
df = pd.read_csv('./Data/Fishing.csv', index_col=0)
df.head()

,Unnamed: 0,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income
0,1,charter,182.930,0.5391,157.930,157.930,157.930,182.930,0.0678,0.0503,0.2601,0.5391,7083.3317
1,2,charter,34.534,0.4671,15.114,15.114,10.534,34.534,0.1049,0.0451,0.1574,0.4671,1249.9998
2,3,boat,24.334,0.2413,161.874,161.874,24.334,59.334,0.5333,0.4522,0.2413,1.0266,3749.9999
3,4,pier,15.134,0.0789,15.134,15.134,55.930,84.930,0.0678,0.0789,0.1643,0.5391,2083.3332
4,5,boat,41.514,0.1082,106.930,106.930,41.514,71.014,0.0678,0.0503,0.1082,0.3240,4583.3320

In [135]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.head()

,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income
0,charter,182.930,0.5391,157.930,157.930,157.930,182.930,0.0678,0.0503,0.2601,0.5391,7083.3317
1,charter,34.534,0.4671,15.114,15.114,10.534,34.534,0.1049,0.0451,0.1574,0.4671,1249.9998
2,boat,24.334,0.2413,161.874,161.874,24.334,59.334,0.5333,0.4522,0.2413,1.0266,3749.9999
3,pier,15.134,0.0789,15.134,15.134,55.930,84.930,0.0678,0.0789,0.1643,0.5391,2083.3332
4,boat,41.514,0.1082,106.930,106.930,41.514,71.014,0.0678,0.0503,0.1082,0.3240,4583.3320

In [136]:
df['mode'].unique()

array(['charter', 'boat', 'pier', 'beach'], dtype=object)

In [140]:
df.groupby('mode')['income'].agg(['count', 'min', 'max', 'mean', 'median'])

         count        min        max         mean     median
mode
beach      134  416.66668  12499.998  4051.616731  3749.9999
boat       418  416.66668  12499.998  4654.106543  3749.9999
charter    452  416.66668  12499.998  3880.899520  3749.9999
pier       178  416.66668  12499.998  3387.172123  2916.6666

In [143]:
df.describe()

,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income
count,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000
mean,52.081975,0.389368,103.422005,103.422005,55.256570,84.379244,0.241011,0.162224,0.171215,0.629368,4099.337054
std,53.829970,0.560596,103.641042,103.641042,62.713444,63.544650,0.190752,0.160390,0.209789,0.706114,2461.964060
min,1.290000,0.000200,1.290000,1.290000,2.290000,27.290000,0.067800,0.001400,0.000200,0.002100,416.666680
25%,15.870000,0.036100,26.656500,26.656500,13.122000,42.896000,0.067800,0.050300,0.023300,0.021900,2083.333200
50%,37.896000,0.164300,74.628000,74.628000,33.534000,61.607000,0.253700,0.078900,0.089700,0.421600,3749.999900
75%,67.513000,0.533300,144.144000,144.144000,72.402000,102.774000,0.533300,0.149800,0.241300,1.026600,5416.666700
max,666.110000,2.310100,843.186000,843.186000,666.110000,691.110000,0.533300,0.452200,0.736900,2.310100,12499.998000

In [145]:
df['log_income'] = df['income'].apply(np.log)
df.head()

,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income,log_income
0,charter,182.930,0.5391,157.930,157.930,157.930,182.930,0.0678,0.0503,0.2601,0.5391,7083.3317,8.865500
1,charter,34.534,0.4671,15.114,15.114,10.534,34.534,0.1049,0.0451,0.1574,0.4671,1249.9998,7.130899
2,boat,24.334,0.2413,161.874,161.874,24.334,59.334,0.5333,0.4522,0.2413,1.0266,3749.9999,8.229511
3,pier,15.134,0.0789,15.134,15.134,55.930,84.930,0.0678,0.0789,0.1643,0.5391,2083.3332,7.641724
4,boat,41.514,0.1082,106.930,106.930,41.514,71.014,0.0678,0.0503,0.1082,0.3240,4583.3320,8.430182

In [146]:
df['pdiff'] = df[['price', 'pbeach']].apply(lambda x: abs(x[0] - x[1]), axis=1)
df.head()

,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income,log_income,pdiff
0,charter,182.930,0.5391,157.930,157.930,157.930,182.930,0.0678,0.0503,0.2601,0.5391,7083.3317,8.865500,25.000
1,charter,34.534,0.4671,15.114,15.114,10.534,34.534,0.1049,0.0451,0.1574,0.4671,1249.9998,7.130899,19.420
2,boat,24.334,0.2413,161.874,161.874,24.334,59.334,0.5333,0.4522,0.2413,1.0266,3749.9999,8.229511,137.540
3,pier,15.134,0.0789,15.134,15.134,55.930,84.930,0.0678,0.0789,0.1643,0.5391,2083.3332,7.641724,0.000
4,boat,41.514,0.1082,106.930,106.930,41.514,71.014,0.0678,0.0503,0.1082,0.3240,4583.3320,8.430182,65.416

In [147]:
df.groupby('mode').agg({'price': 'mean'})

             price
mode
beach    35.699493
boat     41.606813
charter  75.096942
pier     30.571326

In [148]:
df.groupby('mode')['price'].agg('mean')

mode
beach      35.699493
boat       41.606813
charter    75.096942
pier       30.571326
Name: price, dtype: float64

In [149]:
df.groupby('mode')['price'].agg(lambda x: x.median() - x.mean())

mode
beach     -16.391493
boat      -17.004813
charter   -18.226942
pier      -13.942326
Name: price, dtype: float64

In [150]:
df.sort_values(['income'], ascending=False)

,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income,log_income,pdiff
1006,boat,37.896,0.0531,227.376,227.376,37.896,62.896,0.2537,0.1498,0.0531,0.0052,12499.99800,9.433484,189.480
377,boat,328.432,0.0023,511.596,511.596,328.432,352.432,0.1049,0.0451,0.0023,0.0046,12499.99800,9.433484,183.164
556,boat,37.896,0.2413,581.072,581.072,37.896,72.896,0.5333,0.4522,0.2413,1.0266,12499.99800,9.433484,543.176
580,beach,37.896,0.0678,37.896,37.896,170.532,199.532,0.0678,0.0789,0.0014,0.0029,12499.99800,9.433484,0.000
1085,boat,37.896,0.7369,227.376,227.376,37.896,62.896,0.2537,0.1498,0.7369,2.3101,12499.99800,9.433484,189.480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,pier,23.736,0.1498,23.736,23.736,23.736,42.236,0.2537,0.1498,0.0233,0.0219,416.66668,6.032287,0.000
383,charter,61.574,1.0266,65.016,65.016,26.574,61.574,0.5333,0.4522,0.2413,1.0266,416.66668,6.032287,3.442
374,charter,51.832,0.2421,26.832,26.832,26.832,51.832,0.0678,0.0052,0.1491,0.2421,416.66668,6.032287,25.000
371,pier,20.898,0.0789,20.898,20.898,20.898,49.898,0.0678,0.0789,0.1643,0.5391,416.66668,6.032287,0.000
1180,beach,36.636,0.5333,36.636,36.636,61.146,96.146,0.5333,0.4522,0.1665,0.3975,416.66668,6.032287,0.000

In [151]:
df.sort_values(['price', 'income'], ascending=False)

,mode,price,catch,pbeach,ppier,pboat,pcharter,cbeach,cpier,cboat,ccharter,income,log_income,pdiff
249,boat,666.110,0.0531,359.022,359.022,666.110,691.110,0.2537,0.1498,0.0531,0.0052,8750.00100,9.076809,307.088
211,charter,387.208,2.3014,115.248,115.248,362.208,387.208,0.2537,0.1498,0.6817,2.3014,7916.66630,8.976725,271.960
446,charter,335.314,1.0266,578.048,578.048,300.314,335.314,0.5333,0.4522,0.2413,1.0266,8750.00100,9.076809,242.734
588,charter,330.072,0.0052,106.112,106.112,305.072,330.072,0.2537,0.1498,0.0531,0.0052,6250.00130,8.740337,223.960
377,boat,328.432,0.0023,511.596,511.596,328.432,352.432,0.1049,0.0451,0.0023,0.0046,12499.99800,9.433484,183.164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,pier,2.290,0.4522,2.290,2.290,70.990,105.990,0.5333,0.4522,0.2413,1.0266,1249.99980,7.130899,0.000
1155,pier,2.290,0.4522,2.290,2.290,70.990,105.990,0.5333,0.4522,0.2413,1.0266,1249.99980,7.130899,0.000
1013,beach,1.290,0.5333,1.290,1.290,39.990,74.990,0.5333,0.4522,0.2413,1.0266,416.66668,6.032287,0.000
1105,pier,1.290,0.4522,1.290,1.290,39.990,74.990,0.5333,0.4522,0.0051,1.0266,416.66668,6.032287,0.000
1157,pier,1.290,0.4522,1.290,1.290,39.990,74.990,0.5333,0.4522,0.1665,0.3975,416.66668,6.032287,0.000

In [152]:
df.isnull().sum()

mode          0
price         0
catch         0
pbeach        0
ppier         0
pboat         0
pcharter      0
cbeach        0
cpier         0
cboat         0
ccharter      0
income        0
log_income    0
pdiff         0
dtype: int64

**pd.read_csv methods**
- Sep - разделитель
- Decimal - позволяет превратить запятую в точку, для работы с числами с плавающей точкой в питоне

In [162]:
df = pd.read_csv('./Data/wgi_fh.csv', sep=';', decimal=',')
df.head()

       country cnt_code  year    va    ps    ge    rq    rl    cc   fh
0        Aruba      ABW  2016  1.27  1.28  0.90  1.35  1.29  1.29  NaN
1      Andorra      ADO  2016  1.20  1.40  1.86  0.87  1.56  1.23  1.0
2  Afghanistan      AFG  2016 -1.09 -2.75 -1.22 -1.33 -1.62 -1.56  6.0
3       Angola      AGO  2016 -1.17 -0.39 -1.04 -1.00 -1.08 -1.41  6.0
4     Anguilla      AIA  2016   NaN  1.31  1.33  0.87 -0.09  1.23  NaN

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   country   214 non-null    object
 1   cnt_code  214 non-null    object
 2   year      214 non-null    int64
 3   va        204 non-null    float64
 4   ps        211 non-null    float64
 5   ge        209 non-null    float64
 6   rq        209 non-null    float64
 7   rl        209 non-null    float64
 8   cc        209 non-null    float64
 9   fh        197 non-null    float64
dtypes: float64(7), int64(1), object(2)
memory usage: 16.8+ KB

In [164]:
df.isnull().sum()

country      0
cnt_code     0
year         0
va          10
ps           3
ge           5
rq           5
rl           5
cc           5
fh          17
dtype: int64

In [165]:
df['country'].unique()

array(['Aruba', 'Andorra', 'Afghanistan', 'Angola', 'Anguilla', 'Albania',
       'Netherlands Antilles (former)', 'United Arab Emirates',
       'Argentina', 'Armenia', 'American Samoa', 'Antigua and Barbuda',
       'Australia', 'Austria', 'Azerbaijan', 'Burundi', 'Belgium',
       'Benin', 'Burkina Faso', 'Bangladesh', 'Bulgaria', 'Bahrain',
       'Bahamas, The', 'Bosnia and Herzegovina', 'Belarus', 'Belize',
       'Bermuda', 'Bolivia', 'Brazil', 'Barbados', 'Brunei Darussalam',
       'Bhutan', 'South Sudan', 'Botswana', 'Central African Republic',
       'Canada', 'Switzerland', 'Chile', 'China', "Côte d'Ivoire",
       'Cameroon', 'Congo, Rep.', 'Cook Islands', 'Colombia', 'Comoros',
       'Cape Verde', 'Costa Rica', 'Cuba', 'Cayman Islands', 'Cyprus',
       'Czech Republic', 'Germany', 'Djibouti', 'Dominica', 'Denmark',
       'Dominican Republic', 'Algeria', 'Ecuador', 'Egypt, Arab Rep.',
       'Eritrea', 'Spain', 'Estonia', 'Ethiopia', 'Finland', 'Fiji',
       'France', 'Micronesia, Fed. Sts.', 'Gabon', 'United Kingdom',
       'Georgia', 'Ghana', 'Guinea', 'Gambia, The', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala',
       'French Guiana', 'Guam', 'Guyana', 'Hong Kong SAR, China',
       'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'India',
       'Ireland', 'Iran, Islamic Rep.', 'Iraq', 'Iceland', 'Israel',
       'Italy', 'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya',
       'Kyrgyz Republic', 'Cambodia', 'Kiribati', 'St. Kitts and Nevis',
       'Korea, Rep.', 'Kuwait', 'Lao PDR', 'Lebanon', 'Liberia', 'Libya',
       'St. Lucia', 'Liechtenstein', 'Sri Lanka', 'Lesotho', 'Lithuania',
       'Luxembourg', 'Latvia', 'Kosovo', 'Macao SAR, China', 'Morocco',
       'Monaco', 'Moldova', 'Madagascar', 'Maldives', 'Mexico',
       'Marshall Islands', 'Macedonia, FYR', 'Mali', 'Malta', 'Myanmar',
       'Mongolia', 'Montenegro', 'Mozambique', 'Mauritania', 'Martinique',
       'Mauritius', 'Malawi', 'Malaysia', 'Namibia', 'Niger', 'Nigeria',
       'Nicaragua', 'Niue', 'Netherlands', 'Norway', 'Nepal', 'Nauru',
       'New Zealand', 'Oman', 'Pakistan', 'Panama', 'Palau', 'Peru',
       'Philippines', 'Papua New Guinea', 'Poland', 'Puerto Rico',
       'Korea, Dem. Rep.', 'Portugal', 'Paraguay', 'Qatar', 'Réunion',
       'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'Saudi Arabia',
       'Sudan', 'Senegal', 'Singapore', 'Solomon Islands', 'Sierra Leone',
       'El Salvador', 'San Marino', 'Somalia', 'São Tomé and Principe',
       'Suriname', 'Slovak Republic', 'Slovenia', 'Sweden', 'Swaziland',
       'Seychelles', 'Syrian Arab Republic', 'Chad', 'Togo', 'Thailand',
       'Tajikistan', 'Turkmenistan', 'Timor-Leste', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Tuvalu',
       'Taiwan, China', 'Tanzania', 'Uganda', 'Ukraine', 'Uruguay',
       'United States', 'Uzbekistan', 'St. Vincent and the Grenadines',
       'Venezuela, RB', 'Virgin Islands (U.S.)', 'Vietnam', 'Vanuatu',
       'West Bank and Gaza', 'Jersey, Channel Islands', 'Yemen, Rep.',
       'Serbia', 'South Africa', 'Congo, Dem. Rep.', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [168]:
df.dropna(inplace=True)

In [169]:
df.shape

(195, 10)

In [178]:
df.sort_values(['cc', 'va'], inplace=True)
df.head()

                    country  year    va    ps    ge    rq    rl    cc   fh
cnt_code
GNQ       Equatorial Guinea  2016 -1.93 -0.19 -1.41 -1.38 -1.44 -1.81  7.0
SOM                 Somalia  2016 -1.83 -2.33 -2.18 -2.27 -2.37 -1.69  7.0
YEM             Yemen, Rep.  2016 -1.65 -2.79 -1.82 -1.48 -1.60 -1.67  6.5
SDN                   Sudan  2016 -1.80 -2.38 -1.41 -1.49 -1.26 -1.61  7.0
SSD             South Sudan  2016 -1.67 -2.42 -2.26 -1.86 -1.69 -1.58  6.5

In [182]:
df['cc_round'] = np.round(df['cc'], 1)
df.head()

,country,year,va,ps,ge,rq,rl,cc,fh,cc_round
cnt_code,,,,,,,,,,
GNQ,Equatorial Guinea,2016,-1.93,-0.19,-1.41,-1.38,-1.44,-1.81,7.0,-1.8
SOM,Somalia,2016,-1.83,-2.33,-2.18,-2.27,-2.37,-1.69,7.0,-1.7
YEM,"Yemen, Rep.",2016,-1.65,-2.79,-1.82,-1.48,-1.60,-1.67,6.5,-1.7
SDN,Sudan,2016,-1.80,-2.38,-1.41,-1.49,-1.26,-1.61,7.0,-1.6
SSD,South Sudan,2016,-1.67,-2.42,-2.26,-1.86,-1.69,-1.58,6.5,-1.6

In [184]:
df['fh'].unique()

array([7. , 6.5, 6. , 5. , 5.5, 4.5, 3. , 3.5, 4. , 2.5, 1.5, 2. , 1. ])

In [187]:
df.groupby('fh')['country'].count()

fh
1.0    47
1.5     9
2.0    22
2.5     7
3.0    19
3.5    17
4.0    10
4.5     7
5.0     7
5.5    17
6.0    10
6.5    13
7.0    10
Name: country, dtype: int64

In [189]:
df['fh_status'] = df['fh'].apply(lambda x: 'free' if x == 1 else ('partly free' if x == 2 else 'not free'))

In [192]:
df.sample(10)

,country,year,va,ps,ge,rq,rl,cc,fh,cc_round,fh_status
cnt_code,,,,,,,,,,,
NZL,New Zealand,2016,1.44,1.49,1.86,2.04,1.93,2.30,1.0,2.3,free
ZAR,"Congo, Dem. Rep.",2016,-1.39,-2.20,-1.51,-1.32,-1.61,-1.33,6.0,-1.3,not free
LSO,Lesotho,2016,0.03,-0.25,-0.80,-0.39,-0.18,-0.02,3.0,-0.0,not free
OMN,Oman,2016,-1.11,0.80,0.19,0.61,0.43,0.37,5.5,0.4,not free
SEN,Senegal,2016,0.37,-0.27,-0.47,-0.14,-0.19,-0.03,2.0,-0.0,partly free
IRL,Ireland,2016,1.29,0.88,1.35,1.74,1.54,1.63,1.0,1.6,free
RUS,Russian Federation,2016,-1.21,-0.89,-0.22,-0.42,-0.80,-0.86,6.0,-0.9,not free
TGO,Togo,2016,-0.51,-0.20,-1.08,-0.79,-0.68,-0.68,4.0,-0.7,not free
VCT,St. Vincent and the Grenadines,2016,1.04,1.01,0.21,0.28,0.41,0.68,1.0,0.7,free
LTU,Lithuania,2016,0.99,0.80,1.09,1.14,1.02,0.67,1.0,0.7,free

In [193]:
df.groupby('fh_status')['country'].count()

fh_status
free            47
not free       126
partly free     22
Name: country, dtype: int64

In [195]:
df.groupby('fh_status')['ps'].agg(['min', 'max', 'mean', 'median'])

              min   max      mean  median
fh_status
free        -0.06  1.49  0.899574    0.93
not free    -2.91  1.53 -0.513095   -0.41
partly free -0.99  1.19  0.261818    0.25